Dev 16 and ekran dodawania donacji
goodwill-ninjas/android pull request #16
Opened 2023-05-31 09:29 UTC by mierzvoj

2023-05-31 11:22 UTC, matgrube requested changes
Please address as many as possible till the end of the day.

2023-05-31 11:22 UTC, matgrube commented on app/schemas/pl.edu.pjatk.goodwill_ninjas.blooddonor_android.database.AppDatabase/1.json
> +<<<<<<< HEAD
conflict

2023-05-31 11:22 UTC, matgrube commented on app/schemas/pl.edu.pjatk.goodwill_ninjas.blooddonor_android.database.AppDatabase/3.json
> +<<<<<<< HEAD
DITTO

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/BottomMenuItem.kt
> +data class BottomMenuItem(val label: String, val icon: ImageVector)
Wait, wasn't that moved to components or something? And it's missing the onclick I guess

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/BottomMenuItem.kt
> +data class BottomMenuItem(val label: String, val icon: ImageVector)
If so, then delete please

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/Globa.kt
> +public class Global {
Do we know what is this class for? I mean - I'm okay, if we can defend that during exam

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDisqualification/AddDiscqualification.kt
> +fun AddDisqualification(
Please, keep the standard for packages. If it's a full view, then it should be moved to "pages"

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDisqualification/AddDisqualificationAdvanced.kt
> +fun AddDisqualificationAdvanced(
DITTO

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDisqualification/AddDisqualificationAdvanced.kt
> +private fun DiscqualificationDetails(onEventDisqualification: (DisqualificationEvent) -> Unit) {
Isn't it a component?

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDonation/AddDonationFirstScreen.kt
> +@Composable
Again, move to components

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDonation/AddDonationFirstScreen.kt
> +        val options = listOf(
Wait, only 4 of those? Can you use the list from the database maybe?

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDonation/AddDonationFirstScreen.kt
> +fun dropDownMenuDonationType(onEvent: (DonationEvent) -> Unit, exchangeViewModel: ExchangeViewModel) {
Again - move to components
You can keep all of the Donation components in /components/donation and disq in /components/disqualification, then it'll make sense in terms of catalogue structure

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/api/Disqualification/DisqualificationApi.kt
> +interface DisqualificationApi {
Uhhh... You can leave it here, but really? Check the API docs and show me the /api/disqualification endpoint allowing GET method.

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/api/Disqualification/DisqualificationApi.kt
> +interface DisqualificationApi {
It's important to understand what you are trying to do as you are doing things.

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/components/SharedViewModel.kt
> +SharedViewModel: ViewModel() {
Empty? Is it used anyhow?
If yes - move to viewModels/sharedViewModel

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/navigation/navigation.kt
> -        topBar = { MytopBar(userName) },
I've literally told you yesterday, that THIS THING NEEDS SOME ATTENTION.

What you did? Just put my changes in a dumpster. I mean it's not a great deal here, but we literally use this line to show Hello Adam if it's a user named Adam and Hello Sylwek if it's a user named Sylwek. 

PAY ATTENTION TO CONFLICTS, keep in mind the work made by others on the way.

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/navigation/navigation.kt
> +//    Scaffold(
Commented code

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/navigation/navigation.kt
> +                if (currentRoute.equals("Add_donation_advanced")) {
That is actually good, but did you change the color and icon for that FAB? It has to be visible, that the way FAB works has changed.

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/pages/mainPage/MainPage.kt
> +//    BloodCard(
And that is because...?

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/storeViewModel/ExchangeStore.kt
> +class ExchangeStore(var context: Context) {
Again - viewModel, then move to viewModels folder

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/storeViewModel/ExchangeViewModel.kt
> +class ExchangeViewModel(private val context: Context) {
DITTO

2023-05-31 11:22 UTC, matgrube commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/util/DateUtil.kt
> +fun getDefaultDateInMillis(): Long {
So building special folder called "util" just for that util? We have "utils" for that.

2023-05-31 17:33 UTC, mierzvoj commented on app/schemas/pl.edu.pjatk.goodwill_ninjas.blooddonor_android.database.AppDatabase/1.json
> +<<<<<<< HEAD
resolved

2023-05-31 17:33 UTC, mierzvoj commented on app/schemas/pl.edu.pjatk.goodwill_ninjas.blooddonor_android.database.AppDatabase/3.json
> +<<<<<<< HEAD
resolved

2023-05-31 17:35 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/BottomMenuItem.kt
> +data class BottomMenuItem(val label: String, val icon: ImageVector)
moved to components. Not sure, what onclick is in this case...

2023-05-31 17:35 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/Globa.kt
> +public class Global {
deleted

2023-05-31 17:38 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDisqualification/AddDiscqualification.kt
> +fun AddDisqualification(
folders created in pages, views moved

2023-05-31 17:38 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDisqualification/AddDisqualificationAdvanced.kt
> +fun AddDisqualificationAdvanced(
folders in pages created, views moved

2023-05-31 17:38 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDisqualification/AddDisqualificationAdvanced.kt
> +private fun DiscqualificationDetails(onEventDisqualification: (DisqualificationEvent) -> Unit) {
moved to components

2023-05-31 17:39 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDonation/AddDonationFirstScreen.kt
> +@Composable
moved to components

2023-05-31 17:40 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDonation/AddDonationFirstScreen.kt
> +        val options = listOf(
having issues with that, but giving my best try

2023-05-31 17:40 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/addDonation/AddDonationFirstScreen.kt
> +fun dropDownMenuDonationType(onEvent: (DonationEvent) -> Unit, exchangeViewModel: ExchangeViewModel) {
added respective folders for donation and disqualification

2023-05-31 17:45 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/api/Disqualification/DisqualificationApi.kt
> +interface DisqualificationApi {
deleted

2023-05-31 17:46 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/components/SharedViewModel.kt
> +SharedViewModel: ViewModel() {
deleted

2023-05-31 18:12 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/navigation/navigation.kt
> +                if (currentRoute.equals("Add_donation_advanced")) {
no, FAB remains grey

2023-05-31 18:15 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/pages/mainPage/MainPage.kt
> +//    BloodCard(
deleted

2023-05-31 18:16 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/storeViewModel/ExchangeStore.kt
> +class ExchangeStore(var context: Context) {
moved

2023-05-31 18:16 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/storeViewModel/ExchangeViewModel.kt
> +class ExchangeViewModel(private val context: Context) {
moved

2023-05-31 18:17 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/util/DateUtil.kt
> +fun getDefaultDateInMillis(): Long {
fixed

2023-05-31 18:25 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/navigation/navigation.kt
> -        topBar = { MytopBar(userName) },
actual state should reflect your comment. If not, please follow up.

2023-05-31 18:27 UTC, mierzvoj commented on app/src/main/java/pl/edu/pjatk/goodwill_ninjas/blooddonor_android/navigation/navigation.kt
> +//    Scaffold(
merged

2023-06-01 05:09 UTC, matgrube approved these changes
LGTM, merge and we'll have the main flow.
Good job, Mate! It's been a tough one, but you did it!

2023-06-01 07:50 UTC, merged